<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56287" started-at="2020-08-10T18:24:38 GMT+05:30" finished-at="2020-08-10T18:25:34 GMT+05:30">
    <groups>
      <group name="WeatherreportingTestcaess">
        <method signature="NewTest.f()[pri:1, instance:testcases.NewTest@2c039ac6]" name="f" class="testcases.NewTest"/>
      </group> <!-- WeatherreportingTestcaess -->
    </groups>
    <test name="Default test" duration-ms="56287" started-at="2020-08-10T18:24:38 GMT+05:30" finished-at="2020-08-10T18:25:34 GMT+05:30">
      <class name="testcases.NewTest">
        <test-method status="PASS" signature="configForWebpageLaunch()[pri:0, instance:testcases.NewTest@2c039ac6]" name="configForWebpageLaunch" is-config="true" duration-ms="13034" started-at="2020-08-10T18:24:38 GMT+05:30" finished-at="2020-08-10T18:24:51 GMT+05:30">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configForWebpageLaunch -->
        <test-method status="SKIP" signature="f()[pri:1, instance:testcases.NewTest@2c039ac6]" name="f" duration-ms="12165" retried="true" started-at="2020-08-10T18:24:51 GMT+05:30" finished-at="2020-08-10T18:25:03 GMT+05:30">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [78] but found [94]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [78] but found [94]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at testcases.NewTest.f(NewTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:testcases.NewTest@2c039ac6]" name="tearDownTest" is-config="true" duration-ms="6002" started-at="2020-08-10T18:25:03 GMT+05:30" finished-at="2020-08-10T18:25:09 GMT+05:30">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="configForWebpageLaunch()[pri:0, instance:testcases.NewTest@2c039ac6]" name="configForWebpageLaunch" is-config="true" duration-ms="11834" started-at="2020-08-10T18:25:09 GMT+05:30" finished-at="2020-08-10T18:25:21 GMT+05:30">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configForWebpageLaunch -->
        <test-method status="FAIL" signature="f()[pri:1, instance:testcases.NewTest@2c039ac6]" name="f" duration-ms="7387" started-at="2020-08-10T18:25:21 GMT+05:30" finished-at="2020-08-10T18:25:28 GMT+05:30">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [78] but found [94]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [78] but found [94]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at testcases.NewTest.f(NewTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:testcases.NewTest@2c039ac6]" name="tearDownTest" is-config="true" duration-ms="5812" started-at="2020-08-10T18:25:28 GMT+05:30" finished-at="2020-08-10T18:25:34 GMT+05:30">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
      </class> <!-- testcases.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
